spring:
  application:
    name: kafka-to-elastic-service
  profiles:
    active: kafka_to_elastic
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-to-elastic-service,config-client
      username: mark
      password: '{cipher}f2667da0dc65cefd56a7285070a1ca2dba3636a8034161058de9f673c5ab65d4'