server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yongs-dev/microservices-mark-config-repository.git
          default-label: main
          username: yongs-dev
          password: '{cipher}a7ba3935b056cc39b08dcf95ffdcf851eb01925bbdadcec2a00398c4261af25e09673dabf9846d268b6da6ebb67eb7f26f592b13c6bf2c2f232eb73960eda8fc'
          clone-on-start: true
    fail-fast: true
  security:
    user:
      name: mark
      password: '{cipher}f2667da0dc65cefd56a7285070a1ca2dba3636a8034161058de9f673c5ab65d4'

logging:
  level:
    root: INFO
    com.microservices.mark: INFO